################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  furtadasdb:
    image: postgres:12
    restart: always
    container_name: furtadasdb
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - ciclovia

  django:
    container_name: django
    restart: always
    build: 
      context: django/
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn -b 0.0.0.0:8000 admin.wsgi
    volumes:
      - ./django:/code
      - ./media:/media

    ports:
      - "8000:8000"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=${DB_HOST}
      - SECRET_KEY=${SECRET_KEY}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - EMAIL_USE_TLS=${EMAIL_USE_TLS}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - EMAIL_MAILGUN_API_URL=${EMAIL_MAILGUN_API_URL}
      - EMAIL_MAILGUN_API=${EMAIL_MAILGUN_API}

    networks:
      - ciclovia
    depends_on:
      - furtadasdb


networks:
  ciclovia:
    external: false
    name: ciclovia
  default:
    driver: bridge
