# Generated by Django 4.0.4 on 2022-05-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documents/')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='documents/')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=280, null=True)),
                ('modelo', models.CharField(blank=True, max_length=280, null=True)),
                ('nro_serie', models.CharField(blank=True, max_length=280, null=True)),
                ('foto', models.ForeignKey(db_column='foto', on_delete=django.db.models.deletion.CASCADE, to='bicicletas.fotos')),
                ('processo_crime', models.ForeignKey(db_column='processo_crime', on_delete=django.db.models.deletion.CASCADE, to='bicicletas.documentos')),
            ],
        ),
    ]
