# Generated by Django 4.0.4 on 2022-05-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0002_alter_documentos_options_alter_fotos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='foto',
            field=models.ForeignKey(blank=True, db_column='foto', null=True, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.fotos'),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='processo_crime',
            field=models.ForeignKey(blank=True, db_column='processo_crime', null=True, on_delete=django.db.models.deletion.CASCADE, to='bicicletas.documentos'),
        ),
    ]
