# Generated by Django 4.0.4 on 2022-05-04 15:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0003_alter_bicicleta_foto_alter_bicicleta_processo_crime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='foto',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
            preserve_default=False,
        ),
    ]
