# Generated by Django 4.0.4 on 2022-05-04 17:24

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0004_alter_bicicleta_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fotos',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='processo_crime',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
