# Generated by Django 4.0.4 on 2022-05-04 17:30

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0005_delete_fotos_alter_bicicleta_processo_crime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicicleta',
            name='processo_crime',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media'), upload_to=''),
        ),
    ]
