# Generated by Django 4.0.4 on 2022-05-04 18:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0006_alter_bicicleta_processo_crime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicicleta',
            name='processo_crime',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='foto',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/fotos'), upload_to=''),
        ),
    ]
