# Generated by Django 4.0.4 on 2022-05-04 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0008_bicicleta_processo_crime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicicleta',
            old_name='processo_crime',
            new_name='comprovativo',
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
