# Generated by Django 4.0.4 on 2022-05-12 10:33

import bicicletas.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0009_rename_processo_crime_bicicleta_comprovativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicicleta',
            name='razao_registo',
            field=models.CharField(choices=[('pertence-me e foi roubada', 'Pertence-me e foi roubada'), ('não me pertence, encontrei-a', 'Não me pertence, encontrei-a')], default='pertence-me e foi roubada', max_length=50),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='comprovativo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='', validators=[bicicletas.models.file_size, django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='foto',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/'), upload_to='', validators=[bicicletas.models.file_size, django.core.validators.FileExtensionValidator(['jpg', 'jpeg'])]),
        ),
    ]
